
version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    
services:
  # Define a grafana service
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
#      - ./config/provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_SERVICE_PORT}:${GRAFANA_SERVICE_PORT}"
    logging: *logging
