version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  app:
    build:
      context: app/
    command: opentelemetry-instrument flask run --port 8082 --host 0.0.0.0
    ports:
      - 8082:8082