receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9978
      http:
        endpoint: 0.0.0.0:9979
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"


  # Collect metrics
  #prometheus:
  #  config:
  #    scrape_configs:
  #      - job_name: "otel-collector"
  #        scrape_interval: 120s
  #        static_configs:
  #          - targets:
  #            - "balance-reader:8080"
  #            - "transaction-history:8080"
  #            - "ledger-writer:8080"
  #        metrics_path: "/z/prometheus"


exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
